### ISSUE TITLE
Has anybody ever had any problems for using this API?

### ISSUE THREAD

**Issue by peoro** [zxol/airbnbapi#19]
The following statement in the project description has scared me away from this project until now:

> "(Ab)using it could result in an account ban"

 - Has anybody ever had any related problems?
 - Has any Airbnb representative ever given an opinion on this?
 - If I use it for listings I'm co-host of, do I just risk getting my account banned, or could I cause problems for the listing and its creator as well?

**Comment by zxol** [comment]
Personally, I have never had a ban due to API use.  

I've had multiple occasions where bugs resulted in things like long messages being spam repeated 20+ times, and other undesirable behavior, and thankfully I never attracted the attention of their security team.

I've heard a case of a management company using the API to spam advertise, and they were blackballed quite aggressively, apparently.  

I haven't heard any official comments or pubilc policy on the matter.  If you do get a ban, you can explain the situation to customer service and hopefully they would be reasonable.  I'm sure they're aware of API use.
